# Code quality workflow

name: Code Quality

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  Shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ShellCheck action
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          version: v0.10.0

  Codespell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Codespell action
        uses: codespell-project/actions-codespell@v2
        with:
          ignore_words_list: rever
        
