# Code quality workflow

name: Tag version

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  Version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Run project-version on itself
        run: ./project-version.sh -l -o version.h -f h -t v

      - name: Checking version
        run: ci-script/check_script_self_version.sh project-version.sh version.h
